config/routes.rb
Checklisthub::Application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :list_shares
  end
    
  resources :lists do
    member do
      put 'clone'
    end
  end
  
  resource  :home, :anonymous_user_registration
  root :to => "home#show"
end

app/models/list.rb
class List
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :items, type: Array
  field :name,  type: String
  field :description, type: String
  field :readers, type: Array, default: []
  field :writers, type: Array, default: []
  field :global_permission, type: String
  field :show_tweet_this, type: Boolean, default: true
  field :show_facebook_like, type: Boolean, default: true
  
  belongs_to :user
  
  default_scope order_by([[:created_at, :desc]])
  before_save    :ensure_item_exists
  before_destroy :remove_all_sharees
  before_create  :set_global_permission
  before_create  :set_sharing_preferences
  after_create   :add_to_list_organizer
  
  class << self    
    def create_first(user)
      items = [
        "Try hitting 'escape' and editing this text. Hit 'escape' to save.",
        "Escape toggles between editing mode and organization mode.",
        "Now hit the down arrow until this line of text is highlighted in blue. Pressing 'control + ]' will indent the line, and 'control + [' will outdent it.",
        "Now highlight this line and hit backspace or delete.",
        "The previous line should be deleted.",
        "'space' toggles the line's checkbox.",
        "'enter' adds a new line, 'shift + enter' adds a new line before this one, and 'control + enter' adds a new indented line.",
        "You can press 'control + up' or 'control + down' to move a line up or down.",
        "Clicking the wrench icon lets you change the list's name and description."
      ].collect{|i| {body: i}}
      
      if user.anonymous?
        children = [
          "Since you're an anonymous user, you can't log in on other browsers or privately share your lists with others.",
          "Once you sign up, you'll be able to use " + I18n.t("site_name") + " fully.",
        ].collect{|i| {body: i}}
        
        items << {body: "For anonymous users:", children: children}
      end
      
      items <<  {body: "Have fun!"}
      
      create(
        name:  I18n.t(:first_list_title),
        user:  user,
        items: items
      )
    end
  end

  def clone(user, name, description)
    json = self.to_json
    json.gsub!(/"status":"checked"/, '"status":""')
    clone_attributes = JSON.parse(json)
    List.create(
      name: name,
      description: description,
      user: user,
      items: clone_attributes["items"]
    )
  end
  
  def add_sharee(user_or_id, permission)
    id, user = User.user_and_id(user_or_id)
    return if user == self.user
    
    if permission == ListPermissions::READ
      self.readers |= [id]
      self.writers -= [id]
    else
      self.writers |= [id]
      self.readers -= [id]
    end
    save

    user.receive_list(self)
  end

  def remove_sharee(user_or_id)
    id, user = User.user_and_id(user_or_id)
    return if user == self.user
    
    self.readers -= [id]
    self.writers -= [id]

    user.remove_list(self)
    save
  end

  def remove_all_sharees
    sharees.each{|s| remove_sharee(s)}
    self.user.remove_list(self)
  end
  

  def as_json(options = {})
    {
      id: id,
      name: name,
      description: description,
      global_permission: global_permission,
      items: items,
      show_facebook_like: show_facebook_like,
      show_tweet_this: show_tweet_this
    }
  end
  
  def sharees
    (readers + writers).collect{|uid| User.find(uid)}
  end
  
  def ensure_item_exists
    if items.blank?
      self.items = [
        {
          body: ""
        }
      ]
    end
  end
  
  def add_to_list_organizer
    self.user.receive_list(self)
  end

  def set_global_permission
    self.global_permission = (self.user && !self.user.anonymous? && ListPermissions::NONE) || ListPermissions::WRITE
  end

  def set_sharing_preferences
    if self.user.anonymous?
      self.show_tweet_this = true
      self.show_facebook_like = true
    else
      self.show_tweet_this = false
      self.show_facebook_like = false
    end
    true
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :clone]
   
  def index
    if current_user.lists.empty?
      List.create_first(current_user)
    end
    redirect_to current_user.last_viewed_list || current_user.lists.first
  end
  
  def show    
    begin
      @list = List.find(params[:id])
    rescue Mongoid::Errors::DocumentNotFound
      @list = nil
    end

    @list = nil unless can?(:read, @list)
    current_user.update_attribute(:last_viewed_list_id, @list.id) if @list && @list.user == current_user
    @lists = current_user.lists_organized_instantiated if user_signed_in?
  end
    
  def create
    list = current_user.lists.create(name: params[:name], description: params[:description])
    redirect_to(list)
  end
  
  def update
    @list = List.find(params[:id])
    if can?(:modify_items, @list)
      # ensure that read-write user doesn't try to modify something
      # other than items
      if can?(:modify_properties, @list)
        list_params = params[:list]
      else
        list_params = {items: params[:list][:items]}
      end
      
      @list.update_attributes(list_params)
      @list.save
      render :status => 200, :text => "success"
    else
      render :status => 401, :text => "insufficient permissions"
    end
  end

  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def clone
    create_anonymous_user
    @list = List.find(params[:id])
    new_list = @list.clone(current_user, params[:name], params[:description])
    redirect_to(new_list)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def list_shares(list)
    list.sharees.collect do |u|
      {
        user_id: u.id.to_s,
        username: u.username,
        id: list.id.to_s,
        permission: u.permission_for(list)
      }
    end
  end

  def owner?(list)
    list.user == @current_user
  end

  def permissions_for(list)
    @permissions ||= {
      :read => can?(:read, list),
      :modify_items => can?(:modify_items, list),
      :modify_properties => can?(:modify_properties, list),
      :add_sharees => can?(:add_sharees, list)
    }
  end
end

app/views/lists/_form.html.haml
- name ||= nil
- description ||= nil
.clearfix
  %label{:for => "name"} List Name
  .input
    %input.span8.input.name{:name => "name", :value => name || @list.name}
.clearfix
  %label{:for => "description"} List Description
  .input
    %textarea.span8.description{:rows => 4, :name => "description"}= description || @list.description

app/views/lists/_list.html.haml
#properties
  %h2
    %span.name= @list.name
    %ul.pull-right.page-selector
      - if can?(:modify_properties, @list)
        %li.btn.delete{:title => "Delete"}
          %li.separator &bull;
      %li.btn.clone{"data-page-name" => "clone", :title => "Clone"}
      - if can?(:modify_properties, @list)
        %li.btn.settings{"data-page-name" => "settings", :title => "Settings"}
      %li.btn.list.active{"data-page-name" => "list", :title => "List"}
  
  - unless owner?(@list)
    = author(@list)

  - if @list.show_tweet_this || @list.show_facebook_like
    .shares.clearfix
      - if @list.show_tweet_this
        :javascript
          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        %a.twitter-share-button{href: "https://twitter.com/share", "data-text" => "Check out this list: \"#{@list.name}\" from #{url_for @list} @checklisthub" }
    
      - if @list.show_facebook_like
        :javascript
          (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=44575410254";
          fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
        #fb-root
        .fb-like{"data-href" => list_url(@list), "data-send" => "true", "data-layout" => "button_count", "data-width" => "450"}

  .description.clearfix
    = @list.description
.row
  #pages.span
    .row
      #app.page.span14
        #commands
          %p
            Keyboard Commands
            - if user_signed_in?
              == (<a href="#" class="toggle">#{preferences["show-commands"] ? "hide" : "show"}</a>)    
          %table.bordered-table{:style => ("display:none" if user_signed_in? && !preferences["show-commands"]) }
            %tr
              %td <span class="key">enter</span>
              %td save current line and add new line below
            %tr
              %td <span class="key">shift</span> + <span class="key">enter</span>
              %td save current line and add new line above
            %tr
              %td <span class="key">ctrl</span> + <span class="key">enter</span>
              %td save current line and add new line, indented
            %tr
              %td <span class="key">esc</span>
              %td toggle editing
            %tr
              %td <span class="key">backspace</span>, <span class="key">del</span>
              %td delete line
            %tr
              %td <span class="key">space</span>
              %td toggle complete
            %tr
              %td <span class="key">&#8593;</span>
              %td select previous line
            %tr
              %td <span class="key">&#8595;</span>
              %td select next line
            %tr
              %td <span class="key">ctrl</span> + <span class="key">&#8593;</span>
              %td move line up
            %tr
              %td <span class="key">ctrl</span> + <span class="key">&#8595;</span>
              %td move line down
            %tr
              %td <span class="key">ctrl</span> + <span class="key">]</span>
              %td indent
            %tr 
              %td <span class="key">ctrl</span> + <span class="key">[</span>
              %td outdent
      - if can?(:modify_properties, @list)
        #properties-form.page.span14
          %h3 List Settings
          %form.form-stacked
            = render :partial => 'form'
          .row
            .span8
              %h4 Access
              - if anonymous?
                .alert-message.block-message
                  %p Once you've signed up, your Access settings will be saved. In the mean time, the interface will continue to work so you can get a feel for it.
              %table.bordered-table#access
                %thead
                  %tr
                    %th User
                    %th Read
                    %th Write
                    %th No Access
                %tbody
                  %tr.everyone
                    %td everyone
                    %td.option.read{:class => ("selected" if @list.global_permission == ListPermissions::READ)}
                    %td.option.write{:class => ("selected" if @list.global_permission == ListPermissions::WRITE)}
                    %td.option.none{:class => ("selected" if @list.global_permission == ListPermissions::NONE)}
              %p Enter username to share this list
              %input#username
            .span6 
              %h4 Sharing
              %ul.sharing
                %li
                  %label
                    %input#show-tweet-this{type: "checkbox", name:"show-tweet-this", checked: @list.show_tweet_this}
                    Show "tweet this" button
                %li
                  %label
                    %input#show-facebook-like{type: "checkbox", name:"show-facebook-like", checked: @list.show_facebook_like}
                    Show "like this" facebook button
                    

      #clone.page.span14
        %h3 Clone List
        = form_tag clone_list_path(@list), :method => "put", :class => "form-stacked" do
          = render :partial => 'form'
          %input.btn.primary{:type => "submit", :value => "Clone List"}      

app/views/lists/_not_findable.html.haml
%h2 That list could not be found.

app/views/lists/show.html.haml
- @body_id = "list"
- if @list
  - add_title_piece(@list.name)
  :javascript
    App.data.list = #{@list.to_json}
    App.data.listShares = #{can?(:modify_properties, @list) ? JSON.generate(list_shares(@list)) : "null"}
  = render :partial => 'list'
- else
  = render :partial => 'not_findable'

:javascript
  App.data.user = #{current_user.to_json}
  App.data.permissions = #{permissions_for(@list).to_json}
  App.setup()

#new.modal
  .modal-header
    %a.close{:href => "#"} x
    %h3 New List
  .modal-body
    = form_tag lists_path, :method => "post", :class => "form-stacked" do
      = render :partial => 'form', :locals => {name: 'New List', description: ""}
  .modal-footer
    %a.btn.primary{:href => "#"}Save
    %a.btn.secondary.cancel{:href => "#"}Cancel


- content_for :sidebar do
  - if @lists
    .organizer
      %h5 Lists
      %ul.lists
        - @lists.each do |list|
          %li{"data-list-id" => list.id, class: "#{("selected" if @list == list)}"}
            = link_to list.name, list_path(list)
            - unless owner?(list)
              = author(list, false)
      
      .add
        %a{:href => "#", "data-controls-modal" => "new", "data-backdrop" => "true"}+ Create New List
  - else
    = form_tag anonymous_user_registration_path, :class => "form-stacked create" do
      %p
        %button.success.btn.large Create Checklist Now
    
  - if anonymous?
    #to-anonymous.alert-message.block-message
      %p
        %strong Hi anonymous user!
      %p As an anonymous user, you can add lists and share them with others by giving them your list's URL.
      
      %p
        == If you like #{I18n.t("site_name")}, please do #{contextual_sign_up}. All the lists you've made will stay with your new account, and you'll be able to:
      
      %ul
        %li Log in from any browser
        %li Create private lists
        %li Keep track of other people's lists
        %li Privately share your lists with others