config/routes.rb
Checklisthub::Application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :list_shares
  end
    
  resources :lists do
    member do
      put 'clone'
    end
  end
  
  resource  :home, :anonymous_user_registration
  root :to => "home#show"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "9e1Ed6tMyWEqscgCs3K1avAE8urSqppecvLIRVVLOOE", :name => "google-site-verification"}/
    %title= title
    = stylesheet_link_tag 'application'
    = javascript_include_tag '/javascripts/jquery-1.7.min.js', '/javascripts/keycode.js', '/javascripts/jquery.hotkeys.js', '/javascripts/underscore.js', '/javascripts/backbone.js', "/javascripts/bootstrap-modal", '/javascripts/jquery-ui-1.8.16.custom.min.js', '/javascripts/jquery.nestedSortable.js', '/javascripts/bootstrap-twipsy.js'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    %link{:rel => "icon", :type => "image/png", :href => "/images/259-list.png"}
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-27871429-1']);
      _gaq.push(['_trackPageview']);
      
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    
  %body{:id => @body_id}
    :javascript
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      
      
    .topbar
      .listfill
        .container-fluid
          %a.brand{:href => "/"}= I18n.t("site_name") 
          - if user_signed_in?
            .pull-right
              - if anonymous?
                #log-out-forever.hide.modal
                  .modal-header
                    %a.close{:href => "#"}x
                    %h3 End your session?
                  .modal-body
                    Are you sure you want to end your session? Since you don't have an account, you won't be able to access your lists again. If you
                    = succeed "," do
                      = contextual_sign_up
                    your lists can be retrieved and you'll be able to sign in again.
                  .modal-footer
                    %a.btn.danger{:href => destroy_user_session_path}End Session
                    %a.btn.secondary.cancel{:href => "#"}Cancel
                  
                %p
                  = link_to "sign up", edit_anonymous_user_registration_path(current_user)
                  &bull;
                  %a{:href => "#", "data-controls-modal" => "log-out-forever", "data-backdrop" => "true"}end anonymous session
              - else
                %p
                  == logged in as #{link_to current_user.username, edit_user_registration_path(current_user)}
                  &bull;
                  = link_to "logout", destroy_user_session_path
              
          - else
            %form.pull-right{:action => user_session_path, :method => "post"}
              %input.input-small{:placeholder => "Username", :type => "text"}/
              %input.input-small{:placeholder => "Password", :type => "password"}/
              %button.btn{:type => "submit"} Log in
    .container-fluid
      .sidebar
        = yield :sidebar
      #main
        .row
          .span14
            = yield

app/views/layouts/spare.html.haml
!!!
%html{:id => @html_id || "spare"}
  %head
    %meta{:content => "9e1Ed6tMyWEqscgCs3K1avAE8urSqppecvLIRVVLOOE", :name => "google-site-verification"}/
    %title= I18n.t("site_name")
    = stylesheet_link_tag 'application'
    = csrf_meta_tag
    %link{:rel => "icon", :type => "image/png", :href => "/images/259-list.png"}
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-27871429-1']);
      _gaq.push(['_trackPageview']);
      
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    
  %body
    .wrapper
      = yield